# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20170503_1206'),
        ('voucher', '0004_auto_20161115_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='offer_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offer.OfferGroup', verbose_name='Offer Groups'),
        ),
    ]
