# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-06-13 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_auto_20161115_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucher',
            options={'ordering': ('-offers__offer_group__priority', '-offers__priority', 'pk')},
        ),
    ]
