# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-12 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0005_voucher_offer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='offer_group',
        ),
    ]
