workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - thelab-arm64

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  POSTGRES_HOST_AUTH_METHOD: 'trust'

stages:
  - test
  - release

services:
  - postgres:latest@sha256:a02db8cac496f15b094798a38254f14d6e00741f709360e5e00bb6668ea31636
  - redis:latest@sha256:344e3945a0b431c8ff1eecd58c5573538126bd756f02fc7e218ddf1fc2546366

cache:
  key: '$CI_PROJECT_NAME'
  paths:
    - node_modules
    - $HOME/.cache/pip

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.9.0
    inputs:
      pkg_dir: server/


lint_typescript:
  stage: test
  image: node:24@sha256:934240a162082fd8b8a2f90cd5114446443f1eba1c5378f6687167ca405e6584
  script:
    - cd client/
    - NODE_ENV=dev npm i
    - npm run lint
    - NODE_ENV=production node_modules/.bin/webpack

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  script:
    - cd server/
    - uv sync --all-extras
    - uv run tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  parallel:
    matrix:
      - IMAGE: "3.13"
        TOX_SKIP_ENV: "^(?!py313-)"
      - IMAGE: "3.14"
        TOX_SKIP_ENV: "^(?!py314-)"
