workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - thelab-arm64

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  POSTGRES_HOST_AUTH_METHOD: 'trust'

stages:
  - test
  - release

services:
  - postgres:latest@sha256:8ff36f3c66371cba71d20ceedccfc3de9669a68737607888c4ef0af93abe8e39
  - redis:latest@sha256:f4104a06888b913545b999840715813e5444fb8717b26d2c84d935ef2c71cd6c

cache:
  key: '$CI_PROJECT_NAME'
  paths:
    - node_modules
    - $HOME/.cache/pip

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.8.4
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.8.4
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.8.4
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.8.4
    inputs:
      pkg_dir: server/


lint_typescript:
  stage: test
  image: node:24@sha256:8530f76a96d88820d288761f022e318970dda93d01536919fbc16076b7983e63
  script:
    - cd client/
    - NODE_ENV=dev npm i
    - npm run lint
    - NODE_ENV=production node_modules/.bin/webpack

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  script:
    - cd server/
    - uv sync --all-extras
    - uv run tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  parallel:
    matrix:
      - IMAGE: "3.13"
        TOX_SKIP_ENV: "^(?!py313-)"
      - IMAGE: "3.14"
        TOX_SKIP_ENV: "^(?!py314-)"
