workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - thelab-arm64

variables:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ''
  POSTGRES_HOST_AUTH_METHOD: 'trust'

stages:
  - test
  - release

services:
  - postgres:latest@sha256:1a5b3e745bbd82d6deb146505e504da3c2f248cac15e431951b148fbe4f8613a
  - redis:latest@sha256:027002f3d4161eb427643e0cc71023b582fb461c6199e699f46db843f0b39fb1

cache:
  key: '$CI_PROJECT_NAME'
  paths:
    - node_modules
    - $HOME/.cache/pip

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-gitlab-release@0.9.0
  - component: gitlab.com/thelabnyc/thelab-ci-components/publish-to-pypi@0.9.0
    inputs:
      pkg_dir: server/


lint_typescript:
  stage: test
  image: node:24@sha256:fdddfb3e688158251943d52eba361de991548f6814007acba4917ae6b512d6be
  script:
    - cd client/
    - NODE_ENV=dev npm i
    - npm run lint
    - NODE_ENV=production node_modules/.bin/webpack

test:
  stage: test
  image: "registry.gitlab.com/thelabnyc/python:${IMAGE}"
  script:
    - cd server/
    - uv sync --all-extras
    - uv run tox
  coverage: '/^TOTAL.+?(\d+\%)$/'
  parallel:
    matrix:
      - IMAGE: "3.13"
        TOX_SKIP_ENV: "^(?!py313-)"
      - IMAGE: "3.14"
        TOX_SKIP_ENV: "^(?!py314-)"
