services:
  postgres:
    image: postgres:latest@sha256:d129b9577d274bb96cbd44d902bdeb1b935c89247d161241e9154cba64e13df4
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:latest@sha256:39353c6a2f310da333374e1290c91805d15a85def073b5090f58e4ac646d284c

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    command: webpack --watch
    environment:
      NODE_ENV: "production"
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp
