services:
  postgres:
    image: postgres:latest@sha256:c5bd032fb659503bf121faf5cea5894dcfece30286a3db59e3c060f3e9f60cb0
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:latest@sha256:9ec28b9626938ae5dd565f3371fafd78d432cc049da5865726cd411dfb196c8d

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    command: webpack --watch
    environment:
      NODE_ENV: "production"
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp
