services:
  postgres:
    image: postgres:latest@sha256:78481659c47e862334611ccdaf7c369c986b3046da9857112f3b309114a65fb4
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  redis:
    image: redis:latest@sha256:7ead790779268b02e27bf6897003c1b9bc60a6bf2a97a40aa2029755465e7b6a

  node:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    command: webpack --watch
    environment:
      NODE_ENV: "production"
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp

  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    volumes:
      - ./client/:/oscarbluelight/client/
      - ./server/bootstrap.sh:/oscarbluelight/server/bootstrap.sh
      - ./server/manage.py:/oscarbluelight/server/manage.py
      - ./server/pyproject.toml:/oscarbluelight/server/pyproject.toml
      - ./server/server.sh:/oscarbluelight/server/server.sh
      - ./server/tox.ini:/oscarbluelight/server/tox.ini
      - ./server/uv.lock:/oscarbluelight/server/uv.lock
      - ./server/oscarbluelight:/oscarbluelight/server/oscarbluelight
      - ./server/sandbox:/oscarbluelight/server/sandbox
      - ./server/tmp:/oscarbluelight/server/tmp
