# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0003_voucher_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="groups",
            field=models.ManyToManyField(
                blank=True, to="auth.Group", verbose_name="User Groups"
            ),
        ),
    ]
