# Generated by Django 2.2.5 on 2019-09-26 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0007_auto_20180601_1348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="end_datetime",
            field=models.DateTimeField(db_index=True, verbose_name="End datetime"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="start_datetime",
            field=models.DateTimeField(db_index=True, verbose_name="Start datetime"),
        ),
    ]
