# Generated by Django 3.2.13 on 2022-06-15 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0010_auto_20210526_1410"),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                (
                    'ALTER TABLE "voucher_voucher_offers" ALTER COLUMN "id" TYPE bigint;',
                    None,
                )
            ],
            reverse_sql=[
                (
                    'ALTER TABLE "voucher_voucher_offers" ALTER COLUMN "id" TYPE integer;',
                    None,
                )
            ],
        )
    ]
