# Generated by Django 3.2.15 on 2022-10-12 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("voucher", "0011_auto_20220615_1024"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="status",
            field=models.CharField(
                default="Open", max_length=64, verbose_name="Status"
            ),
        ),
    ]
