# Generated by Django 5.2.4 on 2025-07-14 17:50

from django.db import migrations
import thelabdb.fields.char


class Migration(migrations.Migration):
    dependencies = [
        ("voucher", "0013_auto_20231012_1143"),
    ]

    operations = [
        migrations.AlterField(
            model_name="voucher",
            name="name",
            field=thelabdb.fields.char.NullCharField(
                help_text="This will be shown in the checkout and basket once the voucher is entered",
                max_length=128,
                unique=True,
            ),
        ),
    ]
