# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 09:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0002_compoundcondition"),
        ("offer", "0002_auto_20151210_1053"),
    ]

    operations = []
