# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-12 10:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0007_auto_20170417_1354"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("priority", models.IntegerField(unique=True)),
            ],
            options={
                "verbose_name": "OfferGroup",
                "ordering": ["priority"],
            },
        ),
        migrations.RemoveField(
            model_name="blacklist",
            name="blacklist",
        ),
        migrations.AlterModelOptions(
            name="conditionaloffer",
            options={"ordering": ["priority"]},
        ),
        migrations.DeleteModel(
            name="BlackList",
        ),
        migrations.DeleteModel(
            name="BlackListObject",
        ),
        migrations.AddField(
            model_name="conditionaloffer",
            name="offer_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.OfferGroup",
            ),
        ),
    ]
