# Generated by Django 3.2.15 on 2022-10-11 22:09

from django.db import migrations
import oscar.models.fields.autoslugfield


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0012_auto_20211020_1037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offergroup",
            name="slug",
            field=oscar.models.fields.autoslugfield.AutoSlugField(
                blank=True,
                editable=False,
                null=True,
                overwrite=True,
                populate_from="name",
                unique=True,
            ),
        ),
    ]
