# Generated by Django 3.2.15 on 2022-10-10 22:09

from django.db import migrations
from django.utils.text import slugify


def slugify_null_offergroup_slug_fields(apps, schema_editor):
    OfferGroup = apps.get_model("offer", "OfferGroup")
    for offer_group in OfferGroup.objects.filter(slug=None):
        offer_group.slug = slugify(offer_group.name)
        offer_group.save()


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0012_auto_20211020_1037"),
    ]

    operations = [
        migrations.RunPython(slugify_null_offergroup_slug_fields),
    ]
