# Generated by Django 3.2.14 on 2022-07-25 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0012_auto_20211020_1037"),
    ]

    operations = [
        migrations.CreateModel(
            name="OfferAdvertisingContent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255, verbose_name="Text")),
                (
                    "is_bogo",
                    models.BooleanField(
                        default=False,
                        help_text="Controls whether or not the related offer should have the BOGO (Buy One, Get One) advertising content.",
                        verbose_name="BOGO?",
                    ),
                ),
                (
                    "offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advertising_content",
                        to="offer.conditionaloffer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Offer Advertising Content",
                "verbose_name_plural": "Offer Advertising Contents",
            },
        ),
    ]
