# Generated by Django 3.2.22 on 2023-10-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0014_drop_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="compoundbenefit",
            name="conjunction",
            field=models.CharField(
                choices=[("AND", "Logical AND"), ("OR", "Logical OR")],
                default="AND",
                help_text="Select the conjunction which will be used to logically join the sub-benefits together. An AND conjunction applies all sub-benefits. An OR conjunction applies the first benefit which results in a non-zero discount (benefits are applied in order of their value, descending).",
                max_length=10,
                verbose_name="Sub-Benefit conjunction type",
            ),
        ),
        migrations.AddField(
            model_name="rangeproductfileupload",
            name="upload_type",
            field=models.CharField(
                choices=[
                    ("included", "Included products upload"),
                    ("excluded", "Excluded products upload"),
                ],
                default="included",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="range",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
    ]
