# Generated by Django 2.1.10 on 2019-07-05 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0016_remove_conditionaloffer_apply_to_displayed_prices"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompoundBenefit",
            fields=[
                (
                    "benefit_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="offer.Benefit",
                    ),
                ),
                (
                    "subbenefits",
                    models.ManyToManyField(
                        help_text="Select the benefits that this compound-benefit will apply.",
                        related_name="parent_benefits",
                        to="offer.Benefit",
                        verbose_name="Sub-Benefits",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compound benefit",
                "verbose_name_plural": "Compound benefits",
            },
            bases=("offer.benefit",),
        ),
    ]
