# Generated by Django 2.1.10 on 2019-07-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0016_remove_conditionaloffer_apply_to_displayed_prices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compoundcondition",
            name="conjunction",
            field=models.CharField(
                choices=[("AND", "Logical AND"), ("OR", "Logical OR")],
                default="AND",
                help_text="Select the conjunction which will be used to logically join the sub-conditions together.",
                max_length=10,
                verbose_name="Sub-Condition conjunction type",
            ),
        ),
        migrations.AlterField(
            model_name="compoundcondition",
            name="subconditions",
            field=models.ManyToManyField(
                help_text="Select the sub-conditions that this compound-condition will combine.",
                related_name="parent_conditions",
                to="offer.Condition",
                verbose_name="Sub-Conditions",
            ),
        ),
        migrations.AlterField(
            model_name="conditionaloffer",
            name="desktop_image",
            field=models.ImageField(
                blank=True,
                help_text="Desktop image used for promo display.",
                null=True,
                upload_to="images/offers/",
                verbose_name="Ad Image (Desktop)",
            ),
        ),
        migrations.AlterField(
            model_name="conditionaloffer",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select which User Groups are eligible for this offer. If none are selected, all users are eligible.",
                to="auth.Group",
                verbose_name="User Groups",
            ),
        ),
        migrations.AlterField(
            model_name="conditionaloffer",
            name="mobile_image",
            field=models.ImageField(
                blank=True,
                help_text="Mobile image used for promo display.",
                null=True,
                upload_to="images/offers/",
                verbose_name="Ad Image (Mobile)",
            ),
        ),
        migrations.AlterField(
            model_name="conditionaloffer",
            name="offer_group",
            field=models.ForeignKey(
                help_text="Select the Offer Group that this offer belongs to. Offer Group controls the order offers are applied in and which offers may be combined together.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="offer.OfferGroup",
                verbose_name="Offer Group",
            ),
        ),
    ]
