# Generated by Django 2.1.10 on 2019-07-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0017_auto_20190705_1245"),
        ("offer", "0017_compoundbenefit"),
    ]

    operations = []
