# Generated by Django 3.0.8 on 2020-07-22 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0019_auto_20190926_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="range",
            name="cache_version",
        ),
    ]
