# Generated by Django 2.2.17 on 2020-11-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offer", "0020_remove_range_cache_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="RangeProductSet",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "managed": False,
            },
        ),
    ]
