# Generated by Django 3.2.22 on 2023-10-12 11:43

from django.db import migrations, models
import django.core.serializers.json


class Migration(migrations.Migration):
    dependencies = [
        ("basket", "0009_line_date_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="line",
            name="tax_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="VAT rate code"
            ),
        ),
        migrations.AlterField(
            model_name="basket",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="line",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lineattribute",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lineattribute",
            name="value",
            field=models.JSONField(
                encoder=django.core.serializers.json.DjangoJSONEncoder,
                verbose_name="Value",
            ),
        ),
    ]
