# Generated by Django 3.1.6 on 2021-02-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("partner", "0005_auto_20190926_1547"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockrecord",
            name="cost_price",
        ),
        migrations.RemoveField(
            model_name="stockrecord",
            name="price_retail",
        ),
        migrations.AlterField(
            model_name="stockrecord",
            name="price_excl_tax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Price",
            ),
        ),
        migrations.RenameField(
            model_name="stockrecord",
            old_name="price_excl_tax",
            new_name="price",
        ),
    ]
