#!/usr/bin/env bash

if [[ $1 = "rebase" ]]; then
    echo "\nRebuiling compiled files post $1..."

    pushd ./client &> /dev/null
    NODE_ENV=production node_modules/.bin/webpack
    popd &> /dev/null

    echo "Adding built files to the last commit"
    git add -u
    git commit --amend --no-edit
fi
