#!/usr/bin/env bash
# Check for built files, and yell at user if not


# Find source files that are marked as modified
sources=`git status -s | grep 'M.*client\/src\/.*'`

# Find built files that have changed (we don't use M because they could be deleted, etc)
built=`git status -s | grep 'server\/src\/oscarbluelight\/static\/oscarbluelight\/'`

# If source files have changed, but not built files, block the commit
if [ -n "$sources" ] &&  [ -z "$built" ]; then
    echo "Please compile static files before committing."
    exit 1
fi

# Check JS formatting
pushd ./client/ &> /dev/null
yarn prettier --check . || echo "Error: Format JS/TS code with prettier before committing."
popd &> /dev/null

# Check Python formatting
pushd ./server/ &> /dev/null
black --check . || echo "Error: Format Python code with black before committing."
popd &> /dev/null
