# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-19 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('offer', '0003_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group', verbose_name='User Groups'),
        ),
    ]
