# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0006_bluelightabsolutediscountbenefit_bluelightcountcondition_bluelightcoveragecondition_bluelightfixedpr'),
    ]

    operations = [
        migrations.AddField(
            model_name='conditionaloffer',
            name='applicable_to_discounted_lines',
            field=models.BooleanField(default=False, help_text='By default, offers are only applied to basket items that do not already have a discount applied to them. Enabling this flag makes it possible to apply this offer to basket items which are already affected by another discount.', verbose_name='Is applicable to already-discounted lines?'),
        ),
    ]
