# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-18 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0007_auto_20170417_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OfferGroup',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='blacklist',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='conditionaloffer',
            name='offer_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='offer.OfferGroup'),
        ),
    ]
