# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0008_auto_20170418_1709'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionaloffer',
            options={'ordering': ['offer_group']},
        ),
    ]
