# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0009_auto_20170419_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionaloffer',
            options={'ordering': ['priority']},
        ),
        migrations.AlterModelOptions(
            name='offergroup',
            options={'ordering': ['priority'], 'verbose_name': 'OfferGroup'},
        ),
        migrations.RenameField(
            model_name='offergroup',
            old_name='order',
            new_name='priority',
        ),
    ]
