# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-26 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0010_auto_20170426_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offergroup',
            name='priority',
            field=models.IntegerField(unique=True),
        ),
    ]
