# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-03 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0011_auto_20170426_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklist',
            name='blacklist',
        ),
        migrations.DeleteModel(
            name='BlackList',
        ),
        migrations.DeleteModel(
            name='BlackListObject',
        ),
    ]
