# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-05-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0012_auto_20170503_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offergroup',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
