# Generated by Django 4.2.16 on 2024-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0027_attributeoption_code_attributeoptiongroup_code_and_more"),
        ("offer", "0016_fixedunitdiscountbenefit_alter_benefit_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="range",
            name="excluded_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Products with these categories are excluded from the range when Includes all products is checked",
                related_name="excludes",
                to="catalogue.category",
                verbose_name="Excluded Categories",
            ),
        ),
    ]
