# Generated by Django 5.2.4 on 2025-07-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offer", "0017_range_excluded_categories"),
    ]

    operations = [
        migrations.RenameModel("RangeProductSetRefreshLog", "ViewRefreshLog"),
        migrations.AddField(
            model_name="viewrefreshlog",
            name="view_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Range Product Set"), (2, "Offer Application Totals")],
                default=1,
            ),
            preserve_default=False,
        ),
        migrations.RemoveIndex(
            model_name="viewrefreshlog",
            name="offer_range_refresh_960290_idx",
        ),
        migrations.AddIndex(
            model_name="viewrefreshlog",
            index=models.Index(
                fields=["view_type", "refreshed_on"],
                name="offer_viewr_view_ty_2d182e_idx",
            ),
        ),
        migrations.AlterModelOptions(
            name="viewrefreshlog",
            options={"ordering": ("-refreshed_on", "view_type")},
        ),
    ]
